### ISSUE TITLE
Add a note about DataPackageR vs datapack?

### ISSUE THREAD

**Issue by maelle** [ropensci/datapack#103]
Since both packages are in the rOpenSci suite it can be a bit confusing when seeing their names.

Example of such a note for another package: https://github.com/ropensci/rredlist#rredlist

Cf https://github.com/ropensci/DataPackageR/issues/47

**Comment by gothub** [comment]
Updated documentation in commit 762b912c7d3a0f0039ca79d9019e374414c1c2e8

**Comment by maelle** [comment]
Thank you!
