### ISSUE TITLE
Consider SHA-256 as the default hash algorithm

### ISSUE THREAD

**Issue by cboettig** [ropensci/datapack#117]
Creating a new `DataObject` generates an S4 object with a `sysmeta` field that uses SHA-1 as the checksum.  SHA-256 might be a more collision-safe default these days.  

```r
new("DataObject", id, format="text/csv", filename=file)
```

Relatedly, it might be nice to let the user select the `checksumAlgorithm`, e.g.

```r
new("DataObject", id, format="text/csv", filename=file, checksum = "SHA-256")
```

**Comment by mbjones** [comment]
Based on our discussion, sounds great to me @cboettig. PR welcome, or we'll try to add this on our next release.

**Comment by gothub** [comment]
SHA-256 is now the default for sysmeta/objects, updated in commit 9303c806d3d2c48ab9cc9ef11c02993fac6ab1f5
