### ISSUE TITLE
Publish the package DOI - "doi:10.5063/F1QV3JGM"

### ISSUE THREAD

**Issue by sbpcs59** [ropensci/datapack#43]
The DOI associated with this package "doi:10.5063/F1QV3JGM" should be published
before the package is submitted to CRAN.

**Comment by sbpcs59** [comment]
This was published from http://ezid.cdlib.org on 2016-03-10 06:05:25 UTC

**Comment by mbjones** [comment]
We will need to update the doi if we change the title of the package. Reopening.

**Comment by sbpcs59** [comment]
@mbjones datapack changes are made and we are ready to update http://ezid.cdlib.org/id/doi:10.5063/F1QV3JGM

**Comment by mbjones** [comment]
@sbpcs59 OK, DOI has been updated.
