### ISSUE TITLE
Update package name per CRAN request

### ISSUE THREAD

**Issue by sbpcs59** [ropensci/datapack#46]
Per CRAN request, the package name will be updated to 'dpack' or 'datapack'.

@mbjones, which one do you prefer?

Downstream packages will have to be updated as well, and tickets will be entered for
- dataone
- recordr

**Comment by mbjones** [comment]
I guess I prefer `datapack`, but Kurt expressed a preference for `dpack`, so that might be smoother sailing.  Your thoughts?

**Comment by sbpcs59** [comment]
@mbjones I also prefer `datapack` as it is clearer and easier to remember. So if lobbying for this
name is worth another round of emails, I think it is worth it. If you think it's not worth another round of
emails, then I'm willing to concede to using `dpack`.

**Comment by mbjones** [comment]
CRAN seems amenable to either.  So, let's try 'datapack' and see if we can get that through.  We'll have to contact ropensci about renaming the repo.

**Comment by sbpcs59** [comment]
The branch 'datapack' contains the package name changes. These changes do not include
an updated ropensci repo directory. The repo references could be updated in a patch release, after
CRAN accepts the initial release.

**Comment by mbjones** [comment]
I would prefer if we include the new directory name, as we don't want the original URLs floating around if we can avoid it.

**Comment by sbpcs59** [comment]
@mbjones @cboettig ok, so the repo name should get changed before re-submission to CRAN. Who at rOpenSci will change the repo dir name to 'datapack'? Yes, because this is the package name that CRAN will accept, it would be confusing to have a different name for the repo dir.

**Comment by cboettig** [comment]
Can do, just say when

On Mon, Mar 21, 2016, 9:24 AM Peter Slaughter <notifications@github.com>
wrote:

> @mbjones <https://github.com/mbjones> @cboettig
> <https://github.com/cboettig> ok, so the repo name should get changed
> before re-submission to CRAN. Who at rOpenSci will change the repo dir name
> to 'datapack'? Yes, because this is the package name that CRAN will accept,
> it would be confusing to have a different name for the repo dir.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ropensci/datapackage/issues/46#issuecomment-199364933>
>
-- 

http://carlboettiger.info

**Comment by mbjones** [comment]
Hi @cboettig --

Thanks, yes please coordinate with Peter and make the change.  We are soooo
close...

Matt

**Comment by cboettig** [comment]
@sbpcs59 just give the word. I believe after the change GitHub will also redirect from the previous repo name for a while anyway.  Will change repo name when you give the word.

**Comment by sbpcs59** [comment]
@cboettig thx, we are ready for the repo name change

**Comment by cboettig** [comment]
done

**Comment by sbpcs59** [comment]
@cboettig @mbjones the package name changes are currently in the 'datapack' branch. Should those
be merged to 'master' now, or when a similar branch is available in downstream packages, for
example dataone? When the changes are on master, dataone users won't be able to pull from github
until they install the updated dataone package that uses the datapack package name.

**Comment by mbjones** [comment]
Go ahead and merge the branch, and let's get the similar needed changes into DataONE today.  Should all be fast because its a simple substitution in a dozen or so files.

**Comment by sbpcs59** [comment]
Package name changes merged to master in commit 1edbdf6343d884c8971757f775464c35b3d048d3. The dataone package has been updated as well.

Note that class names (e.g. "DataPackage") and terminology in documentation has not been changed, 
as that was not requested by CRAN, just the package name change was requested.

**Comment by mbjones** [comment]
@sbpcs59 great

**Comment by sbpcs59** [comment]
Package name changes completed with commit 1edbdf6343d884c8971757f775464c35b3d048d3
