### ISSUE TITLE
Release prep

### ISSUE THREAD

**Issue by gothub** [ropensci/datapack#49]
datapack is ready for any additional evaluation and then release to CRAN.

The following tasks have been completed:
- build / check() has been rerun on all platforms in cran-comments.md
- all 1.0.0 github issues closed
- datapack build tested with current dataone repo

**Comment by sbpcs59** [comment]
@mbjones datapack is ready for re-submission to CRAN.

**Comment by gothub** [comment]
datapack 1.0.1 is now up on CRAN: https://cran.r-project.org/package=datapack
