### ISSUE TITLE
Example in serializePackage() creates files in /tmp

### ISSUE THREAD

**Issue by sbpcs59** [ropensci/datapack#51]
Update the example to use tempdir() and discontinue running of example to
prevent CRAN errors

**Comment by mbjones** [comment]
Plus, be sure to delete the tempdir after the code is done.

**Comment by sbpcs59** [comment]
@mbjones the roxygen example for `serializePackage` has been fixed to use R tempdir(). In 
addition, the roxygen example has been wrapped in `\dontrun{}`.

Fixed in commit 6fc9d92bc022c697f7b58a267406599950ede1e9
