### ISSUE TITLE
BagIt deserialization and validation

### ISSUE THREAD

**Issue by nuest** [ropensci/datapack#58]
Hi! Great package! Will certainly use it and hopefully be able contribute...

A couple of questions only so far:
- #3 mentions deserialization - is that still planned or not important anymore?
- Have you considered implementing BagIt validation, or is that out of scope of this package?

**Comment by gothub** [comment]
@nuest Thanks for pointing this out. Yes, we still need to add a method for BagIt deserialization and
a method for validation. I've re-opened https://github.com/ropensci/datapack/issues/3 with these
items added. We don't have a release date yet, but these items will get added.

**Comment by nuest** [comment]
Would you be open to external contributions in this direction?

**Comment by gothub** [comment]
@nuest Yes, contributions are welcome! This project is hosted by ropensci, so you may wish to have a look at https://ropensci.org/community, and possibly https://github.com/ropensci/onboarding/blob/master/README.md for background info.

**Comment by mbjones** [comment]
Question was answered so closing.
