### ISSUE TITLE
Error in rpattrs[["numberReplicas"]] : subscript out of bounds

### ISSUE THREAD

**Issue by amoeba** [ropensci/datapack#63]
I can't reproduce this bug and I could use some help!

While using a package that uses `datapack`, two of our interns reported this error to me:

```{r}
Error in rpattrs[["numberReplicas"]] : subscript out of bounds`
```

They were using a HEAD install of this package (016c9d3544cce03953e1651f184caea4e887f0fb) rather than the published CRAN version and this was because [this commit](7ea7628ffda4b899387c71f7d9df9d9f4a23f216) fixed a bug they needed fixed. However, it looks like that fix introduced a bug. I had the interns revert back to the CRAN version and everything started working again.

The line of code producing this error only occurs [once in the repo](https://github.com/ropensci/datapack/blob/7ea7628ffda4b899387c71f7d9df9d9f4a23f216/R/SystemMetadata.R#L269) and it looks like it would be caused by the named vector returned by `xmlAttrs(xml[["replicationPolicy"]])` not having an element called `numberReplicas` which should be caused by the `replicationPolicy` element not having that attribute set.

This is really weird because a valid System Metadata document, if it has a `replicationPolicy`, must have values set for `numberReplicas` and `replicationAllowed`. The object in question causing the issue was on arcticdata.io and the PID is arctic-data.9797.1.

I thought this code would reproduce their error:

```{r}
library(dataone)
mn <- MNode("https://arcticdata.io/metacat/d1/mn/v2")
getSystemMetadata(mn, "arctic-data.9797.1")
```

but it doesn't.

I'd like to reproduce the bug before making any code changes but I could at least propose checking that named vector index before accessing it.

Any thoughts?

**Comment by mbjones** [comment]
I looked into this, and its due to the numberReplicas attribute being missing from the system metadata, and therefor an array out of bounds exception was being thrown.  The fix is to test for existence first.  The schema doesn't require the `numberReplicas` attribute, so if it is missing I set the parse routine to set it to 0.
